### PR TITLE
Coding style fixes and add travis CI config

### PR DESCRIPTION
**Pull request by theskumar**
- fix all the flake8 issues, haven't done for `cron/` and should be done at later stage as needed.
- Add travis CI config run the checks on every push. 

This is almost a rewrite of the whole of the codebase, there aren't any logical change but only the changes from readability point of view. This would help spot the bugs and unnecessary code laying around easily. 

The admin need to enable travis for this repository after logging in at https://travis-ci.org/, you can see the travis logs which I've enabled in my repo for this PR at https://travis-ci.org/theskumar/spoken-website/builds/136630880

### CODE REVIEW

**Comment by theskumar** [comment]
This PR has a huge diff, i've broken down them into different commits so that they are easy to visualise. 

_PS: Also, this is perhaps the biggest PR from me ever. But needed to be done._

**Comment by theskumar** [comment]
@pratham920 ping ^^

**Comment by prathamesh920** [comment]
Indeed very big, went through diff roughly, mainly its clean up and no logical change so no issue in merging.
But will once check everything locally and then merge it.
Travis CI will actually help a lot. Will make sure that it is enabled.

**Comment by theskumar** [comment]
@pratham920 any updates on this, I've got another PR blocked because of this.

After merging this I will create another pull-request against `eventsv2`, but right now you see the diff between this pr and upcoming at 
https://github.com/theskumar/spoken-website/compare/coding-style-fixes...theskumar:remove-dbdump-dependency-for-dev

**Comment by prathamesh920** [comment]
@manivel23, please enable travis for this repository.

**Comment by theskumar** [comment]
@prathamesh920 thanks for merging it up! 👍

**Pull request merged**
